<a href="https://colab.research.google.com/github/m-ramaz/machine-learning-practice/blob/main/EDA/Ordinal_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# ordinal encoding unn columns ki hoti hai jo categorical hu aur un me kuch order hu

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("/content/customer.csv")
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [ ]:
df_new=df.iloc[:,2:4]
df_new.head()

    review education
0  Average    School
1     Poor        UG
2     Good        PG
3     Good        PG
4  Average        UG

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(df_new,df['purchased'],test_size=0.3,random_state=0)

In [ ]:
x_train.shape

(35, 2)

In [ ]:
x_test.shape

(15, 2)

In [ ]:
df.shape

(50, 5)

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe=OrdinalEncoder(categories=[['Good','Average','Poor'],['School','UG','PG']])
x_train_scaled=oe.fit_transform(x_train)
x_test_scaled=oe.transform(x_test)

In [ ]:
x_train_scaled_df=pd.DataFrame(x_train_scaled,columns=x_train.columns)
x_test_scaled_df=pd.DataFrame(x_test_scaled,columns=x_test.columns)

In [ ]:
x_test_scaled_df.head(10)

   review  education
0     2.0        0.0
1     0.0        1.0
2     0.0        1.0
3     0.0        2.0
4     0.0        2.0
5     2.0        2.0
6     0.0        0.0
7     2.0        0.0
8     2.0        2.0
9     1.0        1.0

In [ ]:
df.head(10)

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No
5   31  Female  Average    School       Yes
6   18    Male     Good    School        No
7   60  Female     Poor    School       Yes
8   65  Female  Average        UG        No
9   74    Male     Good        UG       Yes